#!/usr/bin/env bash

. "$(dirname -- "$0")/_/husky.sh"

current_branch="$( bin/get_current_branch )"
if [[ "${current_branch}" != "master" ]]; then
    echo "Current branch is not master, skipping pre-push hook"
    exit 0  # nothing to do here
fi

bin/assert_is_ready_to_release
